project:
  type: website
  output-dir: "docs"
  resources:
    - keybase.txt
    - resume.pdf
    - cv.pdf
website:
  title: "Babby Ekumbo MD. MSc."
  site-url: https://babbymed.github.io
  description: "Écologie, Épidémiologie et Data analyses"
  open-graph:
    locale: fr
  twitter-card:
    creator: "babbymed"
  comments:
    utterances:
      repo: babbymed/bbz.dev
  navbar:
    left: 
      - icon: house-fill
        text: "Home"
        file: index.qmd
      - text: "Publication"
        file: publication.qmd
      - text: "Présentation"
        file: presentation.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - icon: folder
        text: "CV"
        file: cv.qmd
      - icon: github
        href: https://github.com/babbymed
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com
      - icon: facebook
        href: https://facebook.com
page-footer:
    left: "© Copyright 2024 Ekumbo Babby. Sauf indication contraire, tous les textes et images sont sous licence CC-BY-NC 4.0."
format:
  html:
    reference-location: document
    theme: 
      dark: [minty, custom.scss]
      light: [minty, custom-light.scss]
    css:
      - styles.css
    toc: true
    toc-depth: 2
    number-sections: true
    #syntax-definitions: 
    #- fomo.xml

    
#mainfont: "'operator ultra italique', sans" 
#fontcolor: "#7E9372"
#linkcolor: "#525878"
#monofont: courrier new
#grid:
   # sidebar-width: 300px
   # body-width: 900px
    #margin-width: 300px
    #gutter-width: 1.5rem
    
    
#format:
#  html:
#    theme:
#      light: flatly
#      dark: darkly