project:
  type: website
  output-dir: "docs"
  resources:
    - keybase.txt
    - resume.pdf
    - cv.pdf

website:
  title: "Babbymed Connect"
  site-url: https://babbymed.github.io
  description: "Écologie, Épidémiologie et Data analyses"
  open-graph: true
  twitter-card: true
  reader-mode: true
  back-to-top-navigation: true
  navbar:
    left: 
      - icon: house-fill
        text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publication.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - text: "À propos"
        file: about.qmd
      - icon: github
        href: https://github.com/babbymed
        menu:
          - text: Source Code
            href: https://code.com
          - text: Report a Bug
            href: https://bugs.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com
      - icon: facebook
        href: https://facebook.com
page-footer: true
  #center:
   # - text: "© Copyright bbz.2025 : Tous droits réservés sous licence CC-BY-NC 4.0."
  #border: "#0d5a60"
  #background: "#164859"
format:
  html:
    theme:
      light: [theme.css, custom.scss,]
      dark: [theme.css, custom-light.scss]
    highlight-style: github-dark
    lang: fr
    meta:
      viewport: "width=device-width, initial-scale=1"
    code-link: true
    anchor-sections: true
    mainfont: "Lato"
    monofont: "Fira Mono"
    footnotes-hover: true
    fontsize: 1em

rss: true
footnotes-hover: true
fontsize: 1em
page-navigation: true
announcement:
    icon: info-circle
    dismissable: true
    content: "Découvrez le nouveau site sur les analyses des données de santé publique et éco-épidémiologie du *EcoData Insight* ! [Cliquez ici pour en savoir plus](https://avt.github.io/posts)."
    type: light
    position: below-navbar

