project:
  type: website
  output-dir: "docs"

website:
  title: "Babby Ekumbo MD. MSc."
  navbar:
    left: 
      - icon: house-fill
        text: "Home"
        file: index.qmd
      - text: "Publication"
        file: publication.qmd
      - text: "Présentation"
        file: presentation.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - icon: folder
        text: "CV"
        file: cv.qmd
      - icon: github
        href: https://github.com/babbymed
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com
      - icon: facebook
        href: https://facebook.com
format:
  html: 
    theme: cyborg 
    css: styles.css
grid:
    sidebar-width: 300px
    body-width: 900px
    margin-width: 300px
    gutter-width: 1.5rem
    
    
#format:
#  html:
#    theme:
#      light: flatly
#      dark: darkly