---
title: "Publications et rédactions scientifiques"
about:
  template: marquee
  links:
    - icon: folder
      text: CV
      href: cv.qmd
    - icon: github
      text: Github
      href: https://github.com/babbymed

title-block-banner: "url('images/fond.jpeg')"
title-block-banner-color: body
lightbox: true
back-to-top-navigation: true
sidebar:
  style: "docked"
  width: 100
  search: true
  contents:
    - section: "Basics"
      contents:
        - index.qmd
        - basics-jupyter.qmd
page-layout: full
format:
  html:
    css: _variables.scss
listing:
  contents: publication.yml
  page-size: 10
  sort: 'issued desc'
  type: grid
  date-format: "MMMM YYYY"
  categories: false
  sort-ui: [date, title, journal-title, position, first]
  #filter-ui: [date, title, journal-title]
  fields: [date, title, journal-title, first, position]
  field-display-names:
    date: Issued
    journal-title: Journal
    position: Rank
    first: "First"
  feed: true
  id: blog-listings
  #contents: posts
draft: false
---

# 🌐Publications {style="color:#007bff"}

[*En tant qu'auteur principal / Directeur ou co-directeur de travaux publiés*]{.underline}

::: panel-tabset
## ^[[Travaux publiés]{.smallcaps}]{.tab-title}^

## 2023 {.tab-title}

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ##### ~[Profil de l'antibiorésistance du microbiote intestinal des poules (Gallus domesticus) errantes dans la commune de Mont-Ngafula à Kinshasa, RD du Congo]{.smallcaps}~ | -   <div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                              |     > -   [Ekumbo Babby](https://www.researchgate.net/profile/Ekumbo-Babby?_sg%5B0%5D=_ou_kewkaZah9pExn-L05__GaiuCZnNtNIr08qiMdPlmo-tNB9fdm2MDrvwqESZNZQlO0FI.7uqgDbWclrPN1g62ZAdKo1w-9DdgXZMkX100ZMHnTxElFogi-sA1mkFZPwWVf6cI3ht3kfSxMgkALEjG73gTJg&_sg%5B1%5D=eXusPhYRDatc6HEpPb4jH67c3sj4g1Fur8YFOW-PRspF31TQFo5Q0VFsFVNZ20iqSGdcEaE.islw189OJXfqbC4CRSqwGcxfjE16yI3qooW44KC6FsIcXlZbiEULH3ZtLS5WM9y9ckLIXKUCcjYg7hx94VfLRw)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                              |     >     Avec : [Bompangue Didier](https://www.researchgate.net/scientific-contributions/Bompangue-Didier-2242362573?_sg%5B0%5D=_ou_kewkaZah9pExn-L05__GaiuCZnNtNIr08qiMdPlmo-tNB9fdm2MDrvwqESZNZQlO0FI.7uqgDbWclrPN1g62ZAdKo1w-9DdgXZMkX100ZMHnTxElFogi-sA1mkFZPwWVf6cI3ht3kfSxMgkALEjG73gTJg&_sg%5B1%5D=eXusPhYRDatc6HEpPb4jH67c3sj4g1Fur8YFOW-PRspF31TQFo5Q0VFsFVNZ20iqSGdcEaE.islw189OJXfqbC4CRSqwGcxfjE16yI3qooW44KC6FsIcXlZbiEULH3ZtLS5WM9y9ckLIXKUCcjYg7hx94VfLRw&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6InB1YmxpY2F0aW9uIiwicGFnZSI6InB1YmxpY2F0aW9uIiwicG9zaXRpb24iOiJwYWdlSGVhZGVyIn19), [Sylvie-Mireille Bambi](https://www.researchgate.net/profile/Sylvie-Mireille-Bambi?_sg%5B0%5D=_ou_kewkaZah9pExn-L05__GaiuCZnNtNIr08qiMdPlmo-tNB9fdm2MDrvwqESZNZQlO0FI.7uqgDbWclrPN1g62ZAdKo1w-9DdgXZMkX100ZMHnTxElFogi-sA1mkFZPwWVf6cI3ht3kfSxMgkALEjG73gTJg&_sg%5B1%5D=eXusPhYRDatc6HEpPb4jH67c3sj4g1Fur8YFOW-PRspF31TQFo5Q0VFsFVNZ20iqSGdcEaE.islw189OJXfqbC4CRSqwGcxfjE16yI3qooW44KC6FsIcXlZbiEULH3ZtLS5WM9y9ckLIXKUCcjYg7hx94VfLRw&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6InB1YmxpY2F0aW9uIiwicGFnZSI6InB1YmxpY2F0aW9uIiwicG9zaXRpb24iOiJwYWdlSGVhZGVyIn19) & [Robert Kisasa](https://www.researchgate.net/profile/Robert-Kisasa?_sg%5B0%5D=_ou_kewkaZah9pExn-L05__GaiuCZnNtNIr08qiMdPlmo-tNB9fdm2MDrvwqESZNZQlO0FI.7uqgDbWclrPN1g62ZAdKo1w-9DdgXZMkX100ZMHnTxElFogi-sA1mkFZPwWVf6cI3ht3kfSxMgkALEjG73gTJg&_sg%5B1%5D=eXusPhYRDatc6HEpPb4jH67c3sj4g1Fur8YFOW-PRspF31TQFo5Q0VFsFVNZ20iqSGdcEaE.islw189OJXfqbC4CRSqwGcxfjE16yI3qooW44KC6FsIcXlZbiEULH3ZtLS5WM9y9ckLIXKUCcjYg7hx94VfLRw&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6InB1YmxpY2F0aW9uIiwicGFnZSI6InB1YmxpY2F0aW9uIiwicG9zaXRpb24iOiJwYWdlSGVhZGVyIn19) |
|                                                                                                                                                                              |     >                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                              |     > -   Journal of Applied Biosciences 181:18941-18961\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                              |     >     DOI : 10.35759/JABs.181.6\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                              |     >     Sur ResearchGate cliquer ici : [here](https://www.researchgate.net/publication/367557205_Profil_de_l'antibioresistance_du_microbiote_intestinal_des_poules_Gallus_domesticus_errantes_dans_la_commune_de_Mont-Ngafula_a_Kinshasa_RD_du_Congo)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                              |     </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## 2021 {.tab-title}

+----------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ##### [Bacterial Pathogens in Cattle Egret (Bubulcus ibis) and Pied Crow (Corvus albus) in Kinshasa, Democratic Republic of the Congo]{.smallcaps} | -   [Robert Kisasa](https://www.researchgate.net/profile/Robert-Kisasa?_sg%5B0%5D=_ou_kewkaZah9pExn-L05__GaiuCZnNtNIr08qiMdPlmo-tNB9fdm2MDrvwqESZNZQlO0FI.7uqgDbWclrPN1g62ZAdKo1w-9DdgXZMkX100ZMHnTxElFogi-sA1mkFZPwWVf6cI3ht3kfSxMgkALEjG73gTJg&_sg%5B1%5D=eXusPhYRDatc6HEpPb4jH67c3sj4g1Fur8YFOW-PRspF31TQFo5Q0VFsFVNZ20iqSGdcEaE.islw189OJXfqbC4CRSqwGcxfjE16yI3qooW44KC6FsIcXlZbiEULH3ZtLS5WM9y9ckLIXKUCcjYg7hx94VfLRw&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6InB1YmxpY2F0aW9uIiwicGFnZSI6InB1YmxpY2F0aW9uIiwicG9zaXRpb24iOiJwYWdlSGVhZGVyIn19) [Ekumbo Babby](https://www.researchgate.net/profile/Ekumbo-Babby?_sg%5B0%5D=_ou_kewkaZah9pExn-L05__GaiuCZnNtNIr08qiMdPlmo-tNB9fdm2MDrvwqESZNZQlO0FI.7uqgDbWclrPN1g62ZAdKo1w-9DdgXZMkX100ZMHnTxElFogi-sA1mkFZPwWVf6cI3ht3kfSxMgkALEjG73gTJg&_sg%5B1%5D=eXusPhYRDatc6HEpPb4jH67c3sj4g1Fur8YFOW-PRspF31TQFo5Q0VFsFVNZ20iqSGdcEaE.islw189OJXfqbC4CRSqwGcxfjE16yI3qooW44KC6FsIcXlZbiEULH3ZtLS5WM9y9ckLIXKUCcjYg7hx94VfLRw) \| \| |
|                                                                                                                                                    | -   [DOI:10.4236/oalib.1107353](DOI:%20https://doi.org/10.4236/oalib.1107353)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                    |     Lire cet article ici : [here](#0) \|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+----------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

[*En tant qu'auteur principal / Directeur ou co-directeur de travaux non publiés*]{.underline}

::: panel-tabset
## ^[[Travaux non publiés]{.smallcaps}]{.tab-title}^

## 2017 {.tab-title}

+------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ##### [Prise en charge des hémorragies au 3ème trimestre de la grossesse, cas de l'Hôpital Général de Wangata en 2017]{.smallcaps} | -   **Co-Directeur de travail de fin de cycle (TFC) :** pour l'obtention du titre de diplôme de Médecine Général, Chirurgie et accouchement à l'Université de Mbandaka **(UNIMBA).\ |
|                                                                                                                                    |     Auteurs:**\                                                                                                                                                                     |
|                                                                                                                                    |     Travail non publié                                                                                                                                                              |
+------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## 2015 {.tab-title}

+----------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| ##### [Détermination des causes du cas d’hémorragie du post-partum du CSR Muanda A année 2015]{.smallcaps}           | -   **Directeur de travail de fin de cycle (TFC) :** pour l'obtention du titre d'infirmière sage-femme, ISETC Muanda, année académique 2015 - 2016.\ |
|                                                                                                                      |     **Auteur:** Mathy NGOMA\                                                                                                                         |
|                                                                                                                      |     Travail non publié                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| ##### [Prise en charge des hémorragies au 3ème trimestre de grossesse dans le cas CSR Muanda A en 2015.]{.smallcaps} | -   **Directeur de travail de fin de cycle (TFC) :** pour l'obtention du titre d'infirmière sage-femme, ISETC Muanda, année académique 2015 - 2016\  |
|                                                                                                                      |     **Auteur:** Arlette MAZEBI\                                                                                                                      |
|                                                                                                                      |     Travail non publié                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+

## 2005 {.tab-title}

+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ##### [Profil clinique de l'alcoolisme du point de vue des lésions digestives à Mbandaka année 2004.]{.smallcaps} | -   Travail de Fin de cycle (TFC) pour l'obtention du titre de diplômé en Sciences Biomédicales, au Centre Universitaire de Mbandaka extension de l'UNIKIN (actuelle Université de Mbandaka).\                                                                                                                                                                                                                                                                                  |
|                                                                                                                   |     **Co-redacteur:** [Ekumbo Babby](https://www.researchgate.net/profile/Ekumbo-Babby?_sg%5B0%5D=_ou_kewkaZah9pExn-L05__GaiuCZnNtNIr08qiMdPlmo-tNB9fdm2MDrvwqESZNZQlO0FI.7uqgDbWclrPN1g62ZAdKo1w-9DdgXZMkX100ZMHnTxElFogi-sA1mkFZPwWVf6cI3ht3kfSxMgkALEjG73gTJg&_sg%5B1%5D=eXusPhYRDatc6HEpPb4jH67c3sj4g1Fur8YFOW-PRspF31TQFo5Q0VFsFVNZ20iqSGdcEaE.islw189OJXfqbC4CRSqwGcxfjE16yI3qooW44KC6FsIcXlZbiEULH3ZtLS5WM9y9ckLIXKUCcjYg7hx94VfLRw), Gbeffa N. Delly, Mbadi M. Jacques\ |
|                                                                                                                   |     Travail non publié                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

# 🖋️Autres activités scientifiques {style="color:#007bff"}

[*Présentations et participation dans des séminaires et conférences :*]{.underline}

## Année 2024 {style="color:#08e5ff"}

::: flex-container
-   [[***Profil de l'antibiorésistance du microbiote intestinal des poules (Gallus domesticus) errantes dans la commune de Mont-Ngafula à Kinshasa, RD du Congo***, **INOHA 2024**]{.smallcaps}]{style="color: #17ddff;"} 

    \| *Présentation des résultats de l'étude au cours du '**Colloque international One Health 2024**' du 28 au 31 Mars à Kinshasa,*

    \| Université de Kinshasa (UNIKIN) Diapositives disponibles : [here](http://www.Colloque%202024%20-%20INOHA%20(ac.cd)){alt="here"}
:::

::: flex-container
-   [[***R: Basic Training*** , **2024**]{.smallcaps}]{style="color: #17ddff;"}

    \| *Introduction to Health Data Analysis (Trainer: The GRAPH Courses, Cohort Q1-2024, Barcelona),*

    \| Diapositives disponibles : [Cliquez ici](http://babbymed.github.io/){alt="here"}
:::

::: flex-container
-   [[***Analyse de l'usage des antipaludiques en Angola***, **2022**]{.smallcaps}]{style="color: #17ddff;"} 

    \| *Présentation des résultats de l'étude l'usage des antipaludiques en Angola,*

    \| Clínica Maimona & Filhos, : [Cliquez ici](http://www.clinicamaimona.com){alt="here"}
:::

## Année 2023 {style="color:#08e5ff"}

::: flex-container
-   [[***Summer School of International Spring School in Global Health***, **2023**]{.smallcaps}]{style="color: #17ddff;"}

    \| *Trainening with ISGlobal: International Spring School in Global Health, Barcelona/Spain – March,*

    \| Instituto de Global Saúde, : [Cliquez ici](http://www.isglobal.com){alt="here"}
:::
